
title: information
email: zachkarol430@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  work in prog
url: "https://zachkarol430.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  zachkarol430
baseurl: ""

author: Zach Karol

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
staticman_url: https://comment-system-zach-karol.herokuapp.com/v2/entry/zachkarol430/zachkarol430.github.io/main/comments
