
title: information
email: zachkarol430@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  work in prog
url: "https://zachkarol430.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  zachkarol430
baseurl: ""

author: Zach Karol

# Build settings

remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
staticman_url: https://comment-system-zach-karol.herokuapp.com/v2/entry/zachkarol430/zachkarol430.github.io/main/comments

repository  : "zachkarol430/zachkarol430.github.io"
comments:
  provider  : "staticman_v2"
  staticman:
    branch    : "main"
    endpoint: https://comment-system-zach-karol.herokuapp.com/v2/entry/zachkarol430/zachkarol430.github.io/main/comments

paginate: 5 # amount of posts to show
paginate_path: /page:num/
    
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      comments: true

# _config.yml (defaults)
include: ["_pages"]

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
